### ISSUE TITLE
Im so doomed! Facing the same issue for 3 hrs

### ISSUE THREAD

**Issue by derek2403** [derek2403/near#26]
Transaction failed: TypedError: Can not sign transactions for account derek2403.testnet on network testnet, no matching key pair exists for this account
    at Account.signTransaction (account.cjs:51:19)
    at async eval (account.cjs:73:34)
    at async exponentialBackoff (exponential-backoff.cjs:8:24)
    at async Account.signAndSendTransaction (account.cjs:72:24)
    at async Contract._changeMethod (contract.cjs:207:27)
    at async MpcContract.requestSignature (mpcContract.js:39:28)
    at async NearEthAdapter.signAndSendTransaction (ethereum.js:71:27)
    at async executeTransaction (Transfer.js:478:18)
    at async showEVMAddress (Transfer.js:528:9)
    
not sure why this error occurs all the time, if not the is the 32 bit error, im tired already, will try again tmrw. Hopefully is not some errors related to other components.

**Comment by JingYuan0926** [comment]
Don't worry, I'll help you with this today. Get some rest!
